modLoader = "javafml"
loaderVersion = "[41,)" # For spawn eggs
license = "All rights reserved"

[[mods]]
modId = "bumpkinbatch"
version = "${file.jarVersion}"
displayName = "Bumpkin Batch"
credits = "The exaggerated swagger of the Rusty Team"
authors = "bobertrd, cfrishausen, TheDarkColour"
description = '''
Entry in the SpookyJam 2021. New pumpkin patch biome. At night it will make your bones rattle...
'''

[[dependencies.bumpkinbatch]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bumpkinbatch]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bumpkinbatch]]
modId = "terrablender"
mandatory = true
versionRange = "[2.0.0,)"
ordering = "NONE"
side = "BOTH"
