modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="bumpkinbatch"
version="${file.jarVersion}"
displayName="Bumpkin Batch"
credits="The exaggerated swagger of the Rusty Team"
authors="bobertrd, cfrishausen, TheDarkColour"
description='''
Entry in the SpookyJam 2021. New pumpkin patch biome. At night it will make your bones rattle...
'''
[[dependencies.bumpkinbatch]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.17,)" # For spawn eggs
    ordering="NONE"
    side="BOTH"
[[dependencies.bumpkinbatch]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]" # has to be 1.16.5 because forge spawn eggs were not added in older versions
    ordering="NONE"
    side="BOTH"
