modLoader="javafml"
loaderVersion="[37,)" # For spawn eggs
license="All rights reserved"

[[mods]]
modId="bumpkinbatch"
version="${file.jarVersion}"
displayName="Bumpkin Batch"
credits="The exaggerated swagger of the Rusty Team"
authors="bobertrd, cfrishausen, TheDarkColour"
description='''
Entry in the SpookyJam 2021
'''
[[dependencies.bumpkinbatch]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.84,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bumpkinbatch]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
